### ISSUE TITLE
Image is not updating since 3 months

### ISSUE THREAD

**Issue by tigitz** [cytopia/docker-php-cs-fixer#12]
Hello, I've tried to understand why the `latest` tag was behind the actual latest version of `php-cs-fixer` and found out that nightly build has been disabled because of inactivity in the repo.

![image](https://user-images.githubusercontent.com/1524501/142781418-19cd762c-ec83-4aaf-8a79-f96662e297e7.png)

It might be interesting to auto-update the repo with CI to avoid this pitfall.

Cheers.

**Comment by cytopia** [comment]
Thanks for the info, I've re-enabled the nightly workflow.

**Comment by tigitz** [comment]
Seems stuck to a 3 months old run still. Maybe I missed something?

Thanks for your guidance.

**Comment by cytopia** [comment]
Looks like the build itself has errors that I will need to fix. I'll keep this issue open until the hotfix is merged.

**Comment by brosua** [comment]
Hi @cytopia ,
the nightly build ran 7month ago. Can you enable it again?

**Comment by cytopia** [comment]
@tigitz @brosua has been fixed via: https://github.com/cytopia/docker-php-cs-fixer/pull/13

**Comment by Orkin** [comment]
Hi @cytopia nightly build for latest php version is not working anymore
