### ISSUE TITLE
Not operational for 4 months - any plans to revive it

### ISSUE THREAD

**Issue by obukhov** [cytopia/docker-php-cs-fixer#9]
Hi! Looking for a docker image to create docker-based pre-commit hook,

In one of the latest version, the PSR12 ruleset was introduced which I want to use
Unfortunately, this repo docker image is not built for a couple of months. 
Are there any plans to restart it or should I look for an alternative?

Thanks, and appreciate your effort to make other's lives easier.

**Comment by cytopia** [comment]
@obukhov thanks for the nudge. Backlog is currently quite huge. I will prioritize this one.

**Comment by cytopia** [comment]
@obukhov  Has been resolved with latest release
